apiVersion: v2
name: canary-checker
description: Kubernetes native, multi-tenant synthetic monitoring system
type: application
version: 0.0.0
appVersion: "master"
maintainers:
  - name: Flanksource
    url: https://www.flanksource.com
icon: https://github.com/flanksource/docs/blob/main/docs/canary-checker/images/canary-checker-icon.svg
dependencies:
  - name: flanksource-ui
    version: "1.0.757"
    repository: https://flanksource.github.io/charts
    condition: flanksource-ui.enabled
